### ISSUE TITLE
drawio 代码缺少 etc/build 目录

### ISSUE THREAD

**Issue by Constaline** [luffyZh/simple-drawio-starter#2]
`drawio-project` 文件夹下缺少 `etc/build` 文件夹，导致执行 `npm run drawio-build` 失败。

需要处理 `drawio-project/.gitignore` 文件对 `build` 文件夹的忽略。

https://github.com/jgraph/drawio/tree/v15.0.3/etc/build

**Comment by luffyZh** [comment]
@Constaline 已修复
