### ISSUE TITLE
为什么项目跑起来了，点进drawio那个路由会显示404啊，还要启动什么环境吗

### ISSUE THREAD

**Issue by zzzhanga** [luffyZh/simple-drawio-starter#4]

**Comment by gwendolyn503** [comment]
请问下您是怎么跑起来的，我安装了依赖后报错
![image](https://github.com/luffyZh/simple-drawio-starter/assets/27008399/80104782-21e7-4c4e-b9b7-b138028ff4ea)

**Comment by gwendolyn503** [comment]
@zzzhanga

**Comment by upcfeather** [comment]
建议详细阅读一下文档，启动有顺序
